apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnf-firewall-deployment
  labels:
    app: cnf-firewall
spec:
  replicas: 4
  selector:
    matchLabels:
      app: cnf-firewall
  template:
    metadata:
      labels:
        app: cnf-firewall
    spec:
      containers:
      - name: cnf-firewall
        image: luisma95/cnf-firewall:1.0
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: cnf-firewall-service
spec:
  selector:
    app: cnf-firewall
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
