apiVersion: v1
kind: Service
metadata:
  name: cnf-firewall-service
  labels:
    app: cnf-firewall
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30001
  selector:
    app: cnf-firewall